name: 'Delete Spawn Data Container'
branding:
  color: purple
  icon: database
description: 'Delete a spawn data container'
inputs:
  dataContainer: 
    description: 'The data container to delete'
    required: true
  additionalArgs:
    description: 'Additional arguments to provide (e.g flags for a command)'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dataContainer }}
    - ${{ inputs.additionalArgs }}